### ISSUE TITLE
Update project plan with feedback from jp

### ISSUE THREAD

**Issue by lucsomers** [After-Dark-Communications/Group-Project-Q1-2022#17]

**Comment by lucsomers** [comment]
- Update research subquestions to fit with the context (be more specific)
- Flow diagram should be updated in consideration with ongoing iteration
-

**Comment by wesje101** [comment]
[Project plan](https://docs.google.com/document/d/1DwxuBb1d1CjRiH739kekQ3HaecU8DMwO/edit?usp=sharing&ouid=109164268024890494268&rtpof=true&sd=true)

**Comment by lucsomers** [comment]
Questions that do not relate to main question moved to other document because they do not belong in this one
