### ISSUE TITLE
Ethical design Short report

### ISSUE THREAD

**Issue by lucsomers** [After-Dark-Communications/Group-Project-Q1-2022#38]

**Comment by lucsomers** [comment]
Designs page
https://fhict.instructure.com/courses/12090/pages/ethical-design-impact-on-humans-and-society?module_item_id=751941

Short report page
https://fhict.instructure.com/courses/12090/assignments/196273?module_item_id=751942

**Comment by wesje101** [comment]
[Ethical design short report](https://docs.google.com/document/d/1UT4erIU6Po4GtOOotd0kkQvf6AGbWrZd/edit?usp=sharing&ouid=109164268024890494268&rtpof=true&sd=true)
