### ISSUE TITLE
Create sprint delivery document

### ISSUE THREAD

**Issue by Irishmun** [After-Dark-Communications/Group-Project-Q1-2022#39]
https://fhict.instructure.com/courses/12090/pages/sprint-delivery-guidelines?module_item_id=751909

**Comment by wesje101** [comment]
[Sprint delivery document](https://docs.google.com/document/d/1QhLZ7ZcBxGRZZbDrHFMndY_OEixqoKA3ItMHQeO8_WU/edit?usp=sharing)
Currently waiting for sprint retrospective
