### ISSUE TITLE
Screen flow diagram

### ISSUE THREAD

**Issue by lucsomers** [After-Dark-Communications/Group-Project-Q1-2022#6]

**Comment by Irishmun** [comment]
[Screenflow diagram (Drive)](https://drive.google.com/file/d/1c94cDLA4L2rDQtyES4MOmVXBemgp4blA/view?usp=sharing)

**Comment by Irishmun** [comment]
Original diagram outdated, new diagram needs to be made. @wesje101

**Comment by wesje101** [comment]
[Updated diagram as of 8-3-2022](https://drive.google.com/file/d/1D17BXqpUpPR8veaORpUKZDZ4GSh8YWnn/view?usp=sharing)
